### ISSUE TITLE
[ISSUE]: B23O7 Voice changer didnt load up, typing error

### ISSUE THREAD

**Issue by Deafilamor** [deiteris/voice-changer#173]
### Voice Changer Version

B23O7

### Operational System

Windows 10

### GPU

NVIDIA RTX 3090

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [ ] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [ ] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

I wanted to try the new version that got avaible like hour ago. Tho getting this error. 

### Application Screenshot

![image](https://github.com/user-attachments/assets/cdc7a248-fd3f-4f8a-bef5-a2967dfe8bc3)

### Logs on console

Traceback (most recent call last):
  File "client.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "main.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "downloader\SampleDownloader.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "voice_changer\RVC\RVCModelSlotGenerator.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "torch\__init__.py", line 148, in <module>
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\Deafilamor\Downloads\Voice changer B2307\voice-changer-windows-amd64-cuda\MMVCServerSIO\_internal\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by deiteris** [comment]
Hi @Deafilamor! Thank you for your report and sorry for inconvenience! Could you check b2309 that should have this issue fixed?
https://github.com/deiteris/voice-changer/releases/tag/b2309

**Comment by Deafilamor** [comment]
Alright , it succefully loaded and launched the aplication . Thanks for fixing it :D
